import type {
  APMetrics,
  ARMetrics,
  Invoice,
  PipelineResponse,
  ExceptionsResponse,
  RemittancesResponse,
  UnappliedResponse,
  AgentActivityResponse,
} from './types';

export const mockAPMetrics: APMetrics = {
  total_invoices: 342,
  awaiting_approval: 18,
  approved: 207,
  blocked: 12,
  posted: 105,
  touchless_rate: 0.71,
  avg_cycle_time_days: 4.2,
  exception_rate: 0.09,
  total_spend: 4_820_340,
  currency: 'USD',
};

export const mockARMetrics: ARMetrics = {
  open_invoices: 128,
  open_ar_amount: 2_140_780,
  past_due_amount: 387_450,
  past_due_rate: 0.18,
  dso_days: 38,
  unapplied_cash: 94_200,
  collections_at_risk: 218_000,
  currency: 'USD',
};

export const mockInvoices: Invoice[] = [
  {
    invoice_id: 'INV-1001',
    vendor_id: 'V-101',
    vendor_name: 'Acme Supplies',
    invoice_date: '2024-07-01',
    due_date: '2024-07-31',
    received_date: '2024-07-02',
    currency: 'USD',
    subtotal: 12000,
    tax_amount: 960,
    total_amount: 12960,
    po_number: 'PO-8801',
    status: 'pending_approval',
    approver: 'Jane Smith',
    exceptions: [],
    line_items: [{ description: 'Office Supplies', quantity: 120, unit_price: 100, amount: 12000 }],
    source_document: 'invoice_1001.pdf',
    extraction_confidence: 0.97,
  },
  {
    invoice_id: 'INV-1002',
    vendor_id: 'V-102',
    vendor_name: 'Global Tech',
    invoice_date: '2024-07-03',
    due_date: '2024-08-02',
    received_date: '2024-07-04',
    currency: 'USD',
    subtotal: 5500,
    tax_amount: 440,
    total_amount: 5940,
    po_number: 'PO-8802',
    status: 'pending_approval',
    approver: 'Bob Jones',
    exceptions: [],
    line_items: [{ description: 'Software Licenses', quantity: 5, unit_price: 1100, amount: 5500 }],
    source_document: 'invoice_1002.pdf',
    extraction_confidence: 0.99,
  },
  {
    invoice_id: 'INV-1047',
    vendor_id: 'V-105',
    vendor_name: 'FastFreight LLC',
    invoice_date: '2024-07-08',
    due_date: '2024-08-07',
    received_date: '2024-07-09',
    currency: 'USD',
    subtotal: 28000,
    tax_amount: 2240,
    total_amount: 30240,
    po_number: 'PO-8850',
    status: 'blocked',
    approver: 'Jane Smith',
    exceptions: [
      { code: 'PRICE_MISMATCH', severity: 'high', message: 'Unit price exceeds PO tolerance by 18%' },
      { code: 'MISSING_RECEIPT', severity: 'medium', message: 'No goods receipt found for line 2' },
    ],
    line_items: [
      { description: 'Freight Services', quantity: 10, unit_price: 2800, amount: 28000 },
    ],
    source_document: 'invoice_1047.pdf',
    extraction_confidence: 0.88,
  },
  {
    invoice_id: 'INV-1003',
    vendor_id: 'V-103',
    vendor_name: 'BuildRight Co.',
    invoice_date: '2024-07-05',
    due_date: '2024-08-04',
    received_date: '2024-07-06',
    currency: 'USD',
    subtotal: 1800,
    tax_amount: 144,
    total_amount: 1944,
    po_number: null,
    status: 'pending_approval',
    approver: 'Alice Brown',
    exceptions: [],
    line_items: [{ description: 'Maintenance Services', quantity: 6, unit_price: 300, amount: 1800 }],
    source_document: 'invoice_1003.pdf',
    extraction_confidence: 0.95,
  },
  {
    invoice_id: 'INV-1004',
    vendor_id: 'V-104',
    vendor_name: 'CloudNet Systems',
    invoice_date: '2024-07-06',
    due_date: '2024-08-05',
    received_date: '2024-07-07',
    currency: 'USD',
    subtotal: 9200,
    tax_amount: 736,
    total_amount: 9936,
    po_number: 'PO-8820',
    status: 'validated',
    approver: 'Bob Jones',
    exceptions: [{ code: 'DUPLICATE_RISK', severity: 'low', message: 'Possible duplicate of INV-0998' }],
    line_items: [{ description: 'Cloud Hosting Q3', quantity: 1, unit_price: 9200, amount: 9200 }],
    source_document: 'invoice_1004.pdf',
    extraction_confidence: 0.93,
  },
];

export const mockPipeline: PipelineResponse = {
  stages: [
    { stage: 'Received', count: 42 },
    { stage: 'Extracted', count: 35 },
    { stage: 'Validated', count: 58 },
    { stage: 'Matched', count: 88 },
    { stage: 'Approval', count: 18 },
    { stage: 'Posted', count: 105 },
  ],
};

export const mockExceptions: ExceptionsResponse = {
  items: [
    { invoice_id: 'INV-1047', document_id: null, code: 'PRICE_MISMATCH', severity: 'high', message: 'Unit price exceeds PO tolerance by 18%', domain: 'ap', amount: 30240 },
    { invoice_id: 'INV-1047', document_id: null, code: 'MISSING_RECEIPT', severity: 'medium', message: 'No goods receipt found for line 2', domain: 'ap', amount: 0 },
    { invoice_id: 'INV-1004', document_id: null, code: 'DUPLICATE_RISK', severity: 'low', message: 'Possible duplicate of INV-0998', domain: 'ap', amount: 9936 },
    { invoice_id: null, document_id: 'REM-2201', code: 'UNMATCHED_PAYMENT', severity: 'high', message: 'Payment of $47,200 could not be matched to open invoices', domain: 'ar', amount: 47200 },
    { invoice_id: null, document_id: 'REM-2205', code: 'PARTIAL_MATCH', severity: 'medium', message: 'Payment matched to 2 of 4 invoices, $12,100 unapplied', domain: 'ar', amount: 12100 },
  ],
  count: 5,
};

export const mockRemittances: RemittancesResponse = {
  items: [
    {
      remittance_id: 'REM-2201',
      customer_id: 'C-301',
      customer_name: 'Meridian Corp',
      payment_date: '2024-07-10',
      payment_amount: 47200,
      currency: 'USD',
      applied_amount: 0,
      unapplied_amount: 47200,
      status: 'unapplied',
      matches: [],
      source_document: 'remittance_2201.pdf',
    },
    {
      remittance_id: 'REM-2202',
      customer_id: 'C-302',
      customer_name: 'Apex Industries',
      payment_date: '2024-07-11',
      payment_amount: 85000,
      currency: 'USD',
      applied_amount: 85000,
      unapplied_amount: 0,
      status: 'applied',
      matches: [
        { ar_invoice_id: 'AR-5501', applied_amount: 45000, confidence: 0.99 },
        { ar_invoice_id: 'AR-5502', applied_amount: 40000, confidence: 0.97 },
      ],
      source_document: 'remittance_2202.pdf',
    },
    {
      remittance_id: 'REM-2205',
      customer_id: 'C-305',
      customer_name: 'Blue Ridge Mfg',
      payment_date: '2024-07-14',
      payment_amount: 33400,
      currency: 'USD',
      applied_amount: 21300,
      unapplied_amount: 12100,
      status: 'partially_applied',
      matches: [
        { ar_invoice_id: 'AR-5510', applied_amount: 21300, confidence: 0.91 },
      ],
      source_document: 'remittance_2205.pdf',
    },
  ],
  count: 3,
};

export const mockUnapplied: UnappliedResponse = {
  items: [mockRemittances.items[0], mockRemittances.items[2]],
  total_unapplied: 59300,
  count: 2,
};

export const mockAgentActivity: AgentActivityResponse = {
  items: [
    { timestamp: '2024-07-15T09:02:11Z', agent: 'DocumentIntelligenceAgent', action: 'Extracted invoice', detail: 'INV-1048 from FastFreight LLC — confidence 94%', status: 'succeeded' },
    { timestamp: '2024-07-15T09:01:55Z', agent: 'ValidationAgent', action: 'Validated 3-way match', detail: 'INV-1046 matched PO-8849 and GR-7721', status: 'succeeded' },
    { timestamp: '2024-07-15T09:00:40Z', agent: 'ExceptionAgent', action: 'Flagged price mismatch', detail: 'INV-1047 — unit price deviation 18%', status: 'running' },
    { timestamp: '2024-07-15T08:58:12Z', agent: 'CashApplicationAgent', action: 'Applied payment', detail: 'REM-2202 → AR-5501 ($45k) + AR-5502 ($40k)', status: 'succeeded' },
    { timestamp: '2024-07-15T08:55:03Z', agent: 'OrchestratorAgent', action: 'Routed approval', detail: 'INV-1045 queued for Jane Smith (>$10k threshold)', status: 'succeeded' },
    { timestamp: '2024-07-15T08:50:30Z', agent: 'CashApplicationAgent', action: 'Failed to match remittance', detail: 'REM-2201 — no open AR invoices found for Meridian Corp', status: 'failed' },
  ],
  count: 6,
};
